// 账户分类数据
export const categories = [
  {
    id: 'email',
    name: '邮箱账户',
    image: '/images/email.png',
    count: 27,
    description: '提供各类优质邮箱账户，包括Gmail、Outlook等',
  },
  {
    id: 'social',
    name: '社交媒体',
    image: '/images/social.png',
    count: 42,
    description: '提供Instagram、Twitter、Facebook等社交媒体账户',
  },
  {
    id: 'streaming',
    name: '流媒体账户',
    image: '/images/streaming.png',
    count: 18,
    description: '提供Netflix、Disney+、Spotify等流媒体账户',
  },
  {
    id: 'gaming',
    name: '游戏账户',
    image: '/images/gaming.png',
    count: 15,
    description: '提供Steam、Epic Games、Origin等游戏平台账户',
  },
  {
    id: 'cloud',
    name: '云存储账户',
    image: '/images/cloud.png',
    count: 9,
    description: '提供Google Drive、Dropbox、OneDrive等云存储账户',
  },
  {
    id: 'other',
    name: '其他账户',
    image: '/images/other.png',
    count: 12,
    description: '提供其他类型的优质账户',
  },
];

// 账户数据
export const accounts = [
  // Gmail 账户
  {
    id: 'gmail-1',
    title: 'Gmail 账户 - 标准版',
    price: 15.99,
    image: '/images/gmail.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 50,
    description: '全新Gmail账户，已完成手机验证，可立即使用。',
    features: ['已完成手机验证', '无需恢复邮箱', '可修改密码', '支持两步验证'],
  },
  {
    id: 'gmail-2',
    title: 'Gmail 账户 - 高级版',
    price: 25.99,
    image: '/images/gmail.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 30,
    description: '高级Gmail账户，已使用6个月以上，已完成所有验证。',
    features: ['账户年龄6个月+', '已完成所有验证', '可用于高级验证', '支持两步验证'],
  },
  {
    id: 'gmail-3',
    title: 'Gmail 账户 - 企业版',
    price: 35.99,
    image: '/images/gmail.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 20,
    description: '企业级Gmail账户，已使用1年以上，适合商业用途。',
    features: ['账户年龄1年+', '企业级信誉', '无限存储空间', '优先客服支持'],
  },
  {
    id: 'gmail-4',
    title: 'Gmail 账户 - 老号',
    price: 45.99,
    image: '/images/gmail.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 15,
    description: '稀有Gmail老号，已使用3年以上，高度可信任。',
    features: ['账户年龄3年+', '高信誉度', '已验证历史', '适合各类平台注册'],
  },
  
  // Office 账户
  {
    id: 'office-1',
    title: 'Office 365 个人版',
    price: 29.99,
    image: '/images/outlook.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 40,
    description: 'Office 365个人版账户，包含Word、Excel、PowerPoint等应用。',
    features: ['1TB OneDrive存储', 'Office应用完整访问权限', '可在5台设备上使用', '技术支持'],
  },
  {
    id: 'office-2',
    title: 'Office 365 家庭版',
    price: 49.99,
    image: '/images/outlook.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 25,
    description: 'Office 365家庭版账户，最多可供6人使用。',
    features: ['每人1TB OneDrive存储', 'Office应用完整访问权限', '每人可在5台设备上使用', '高级安全功能'],
  },
  {
    id: 'office-3',
    title: 'Office 365 商业版',
    price: 59.99,
    image: '/images/outlook.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 20,
    description: 'Office 365商业版账户，适合小型企业使用。',
    features: ['商业级电子邮件', '团队协作工具', '高级安全功能', '全天候技术支持'],
  },
  
  // Outlook 账户
  {
    id: 'outlook-1',
    title: 'Outlook 账户 - 标准版',
    price: 12.99,
    image: '/images/outlook.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 45,
    description: '全新Outlook账户，已完成基础验证，可立即使用。',
    features: ['已完成基础验证', '可修改密码', '支持两步验证', '可用于Microsoft服务'],
  },
  {
    id: 'outlook-2',
    title: 'Outlook 账户 - 高级版',
    price: 22.99,
    image: '/images/outlook.png',
    category: 'email',
    categoryName: '邮箱账户',
    stock: 35,
    description: '高级Outlook账户，已使用6个月以上，已完成所有验证。',
    features: ['账户年龄6个月+', '已完成所有验证', '可用于高级验证', '支持两步验证'],
  },
  
  // Instagram 账户
  {
    id: 'instagram-1',
    title: 'Instagram 账户 - 基础版',
    price: 18.99,
    image: '/images/instagram.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 25,
    description: '全新Instagram账户，已完成手机验证，可立即使用。',
    features: ['已完成手机验证', '无粉丝基础', '可修改密码', '支持两步验证'],
  },
  {
    id: 'instagram-2',
    title: 'Instagram 账户 - 1000粉丝',
    price: 49.99,
    image: '/images/instagram.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 10,
    description: 'Instagram账户，拥有1000+真实粉丝，账户年龄1年以上。',
    features: ['1000+真实粉丝', '账户年龄1年+', '已完成所有验证', '可修改所有信息'],
  },
  {
    id: 'instagram-3',
    title: 'Instagram 账户 - 5000粉丝',
    price: 99.99,
    image: '/images/instagram.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 5,
    description: 'Instagram账户，拥有5000+真实粉丝，账户年龄2年以上。',
    features: ['5000+真实粉丝', '账户年龄2年+', '已完成所有验证', '高互动率'],
  },
  {
    id: 'instagram-4',
    title: 'Instagram 账户 - 10000粉丝',
    price: 199.99,
    image: '/images/instagram.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 3,
    description: 'Instagram账户，拥有10000+真实粉丝，账户年龄3年以上。',
    features: ['10000+真实粉丝', '账户年龄3年+', '蓝V认证', '高互动率'],
  },
  
  // Twitter 账户
  {
    id: 'twitter-1',
    title: 'Twitter 账户 - 基础版',
    price: 16.99,
    image: '/images/twitter.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 30,
    description: '全新Twitter账户，已完成手机验证，可立即使用。',
    features: ['已完成手机验证', '无粉丝基础', '可修改密码', '支持两步验证'],
  },
  {
    id: 'twitter-2',
    title: 'Twitter 账户 - 1000粉丝',
    price: 45.99,
    image: '/images/twitter.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 15,
    description: 'Twitter账户，拥有1000+真实粉丝，账户年龄1年以上。',
    features: ['1000+真实粉丝', '账户年龄1年+', '已完成所有验证', '可修改所有信息'],
  },
  {
    id: 'twitter-3',
    title: 'Twitter 账户 - 5000粉丝',
    price: 89.99,
    image: '/images/twitter.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 8,
    description: 'Twitter账户，拥有5000+真实粉丝，账户年龄2年以上。',
    features: ['5000+真实粉丝', '账户年龄2年+', '已完成所有验证', '高互动率'],
  },
  
  // Facebook 账户
  {
    id: 'facebook-1',
    title: 'Facebook 账户 - 基础版',
    price: 19.99,
    image: '/images/facebook.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 20,
    description: '全新Facebook账户，已完成手机验证，可立即使用。',
    features: ['已完成手机验证', '无好友基础', '可修改密码', '支持两步验证'],
  },
  {
    id: 'facebook-2',
    title: 'Facebook 账户 - 500好友',
    price: 39.99,
    image: '/images/facebook.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 15,
    description: 'Facebook账户，拥有500+真实好友，账户年龄1年以上。',
    features: ['500+真实好友', '账户年龄1年+', '已完成所有验证', '可修改所有信息'],
  },
  {
    id: 'facebook-3',
    title: 'Facebook 账户 - 2000好友',
    price: 79.99,
    image: '/images/facebook.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 10,
    description: 'Facebook账户，拥有2000+真实好友，账户年龄2年以上。',
    features: ['2000+真实好友', '账户年龄2年+', '已完成所有验证', '高互动率'],
  },
  
  // Discord 账户
  {
    id: 'discord-1',
    title: 'Discord 账户 - 基础版',
    price: 14.99,
    image: '/images/discord.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 40,
    description: '全新Discord账户，已完成邮箱验证，可立即使用。',
    features: ['已完成邮箱验证', '无服务器', '可修改密码', '支持两步验证'],
  },
  {
    id: 'discord-2',
    title: 'Discord 账户 - Nitro版',
    price: 29.99,
    image: '/images/discord.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 25,
    description: 'Discord Nitro账户，享受高级功能，已付费1个月。',
    features: ['Nitro会员', '高清视频', '自定义标签', '服务器提升'],
  },
  {
    id: 'discord-3',
    title: 'Discord 账户 - 老号',
    price: 39.99,
    image: '/images/discord.png',
    category: 'social',
    categoryName: '社交媒体',
    stock: 15,
    description: 'Discord老号，已使用2年以上，加入多个优质服务器。',
    features: ['账户年龄2年+', '加入多个服务器', '已完成所有验证', '可修改所有信息'],
  },
  
  // Netflix 账户
  {
    id: 'netflix-1',
    title: 'Netflix 账户 - 标准版',
    price: 29.99,
    image: '/images/netflix.png',
    category: 'streaming',
    categoryName: '流媒体账户',
    stock: 15,
    description: 'Netflix标准账户，支持1080p画质，可同时观看2个屏幕。',
    features: ['1080p高清画质', '同时观看2个屏幕', '支持所有设备', '已付费1个月'],
  },
  {
    id: 'netflix-2',
    title: 'Netflix 账户 - 高级版',
    price: 39.99,
    image: '/images/netflix.png',
    category: 'streaming',
    categoryName: '流媒体账户',
    stock: 10,
    description: 'Netflix高级账户，支持4K画质，可同时观看4个屏幕。',
    features: ['4K超高清画质', '同时观看4个屏幕', '支持所有设备', '已付费1个月'],
  },
  
  // Spotify 账户
  {
    id: 'spotify-1',
    title: 'Spotify Premium 账户',
    price: 22.99,
    image: '/images/spotify.png',
    category: 'streaming',
    categoryName: '流媒体账户',
    stock: 25,
    description: 'Spotify Premium账户，无广告，可下载音乐离线收听。',
    features: ['无广告打扰', '可下载音乐', '高品质音频', '已付费1个月'],
  },
  {
    id: 'spotify-2',
    title: 'Spotify Family 账户',
    price: 32.99,
    image: '/images/spotify.png',
    category: 'streaming',
    categoryName: '流媒体账户',
    stock: 15,
    description: 'Spotify Family账户，最多可供6人使用，所有人都享受Premium特权。',
    features: ['最多6人使用', '所有人享受Premium特权', '独立播放列表', '已付费1个月'],
  },
  
  // Steam 账户
  {
    id: 'steam-1',
    title: 'Steam 账户 - 基础版',
    price: 15.99,
    image: '/images/steam.png',
    category: 'gaming',
    categoryName: '游戏账户',
    stock: 20,
    description: '全新Steam账户，已完成所有验证，可立即使用。',
    features: ['已完成所有验证', '无游戏', '可修改密码', '支持两步验证'],
  },
  {
    id: 'steam-2',
    title: 'Steam 账户 - 10款游戏',
    price: 49.99,
    image: '/images/steam.png',
    category: 'gaming',
    categoryName: '游戏账户',
    stock: 15,
    description: 'Steam账户，包含10款热门游戏，账户年龄1年以上。',
    features: ['10款热门游戏', '账户年龄1年+', '已完成所有验证', '可修改所有信息'],
  },
  {
    id: 'steam-3',
    title: 'Steam 账户 - 30款游戏',
    price: 99.99,
    image: '/images/steam.png',
    category: 'gaming',
    categoryName: '游戏账户',
    stock: 8,
    description: 'Steam账户，包含30款热门游戏，账户年龄2年以上。',
    features: ['30款热门游戏', '账户年龄2年+', '已完成所有验证', '可修改所有信息'],
  },
];

// 热门账户数据
export const featuredAccounts = [
  accounts.find(acc => acc.id === 'gmail-1'),
  accounts.find(acc => acc.id === 'office-1'),
  accounts.find(acc => acc.id === 'instagram-1'),
  accounts.find(acc => acc.id === 'twitter-1'),
  accounts.find(acc => acc.id === 'facebook-1'),
  accounts.find(acc => acc.id === 'discord-1'),
  accounts.find(acc => acc.id === 'netflix-1'),
  accounts.find(acc => acc.id === 'spotify-1'),
].filter(Boolean); 